{
    'name': 'Modulo Alumnos',
    'version': '1.0.0',
    'author': 'Augusto Caceres',
    'sequence': -100,
    'summary': 'Sitema gestor de registro de alumnos',
    'description': """Sistema encargo de gestionar la incripcion de alumnos a diferentes programas""",
    'depends': ['base'],
    'data': [
        'security/ir.model.access.csv',
        'views/menu.xml',
        'views/alumno_views.xml',
        'views/inscripcion_views.xml',
        'views/programa_views.xml',
    ],
    'application': True,
    'installable': True,
    'application': True,
    'licence': 'LGPL-3',
}
